export const BUSINESS_PERFORMANCE_LIST_REQUEST = 'BUSINESS_PERFORMANCE_LIST_REQUEST'
export const BUSINESS_PERFORMANCE_LIST_SUCCESS = 'BUSINESS_PERFORMANCE_LIST_SUCCESS'
export const BUSINESS_PERFORMANCE_LIST_FAIL = 'BUSINESS_PERFORMANCE_LIST_FAIL'


export const BUSINESS_PERFORMANCE_INSERT_REQUEST = 'BUSINESS_PERFORMANCE_INSERT_REQUEST';
export const BUSINESS_PERFORMANCE_INSERT_SUCCESS = 'BUSINESS_PERFORMANCE_INSERT_SUCCESS';
export const BUSINESS_PERFORMANCE_INSERT_FAIL = 'BUSINESS_PERFORMANCE_INSERT_FAIL';

export const BUSINESS_PERFORMANCE_DELETE_REQUEST = 'BUSINESS_PERFORMANCE_DELETE_REQUEST';
export const BUSINESS_PERFORMANCE_DELETE_SUCCESS = 'BUSINESS_PERFORMANCE_DELETE_SUCCESS';
export const BUSINESS_PERFORMANCE_DELETE_FAIL = 'BUSINESS_PERFORMANCE_DELETE_FAIL';

