export const CONTRACT_LIST_REQUEST = 'CONTRACT_LIST_REQUEST'
export const CONTRACT_LIST_SUCCESS = 'CONTRACT_LIST_SUCCESS'
export const CONTRACT_LIST_FAIL = 'CONTRACT_LIST_FAIL'


export const CONTRACT_DELETE_REQUEST = 'CONTRACT_DELETE_REQUEST';
export const CONTRACT_DELETE_SUCCESS = 'CONTRACT_DELETE_SUCCESS';
export const CONTRACT_DELETE_FAIL = 'CONTRACT_DELETE_FAIL';


export const CONTRACT_UPDATE_STATUS_REQUEST = "CONTRACT_UPDATE_STATUS_REQUEST";
export const CONTRACT_UPDATE_STATUS_SUCCESS = "CONTRACT_UPDATE_STATUS_SUCCESS";
export const CONTRACT_UPDATE_STATUS_FAIL = "CONTRACT_UPDATE_STATUS_FAIL";