export const INVESTMENT_LIST_REQUEST = 'INVESTMENT_LIST_REQUEST'
export const INVESTMENT_LIST_SUCCESS = 'INVESTMENT_LIST_SUCCESS'
export const INVESTMENT_LIST_FAIL = 'INVESTMENT_LIST_FAIL'


export const INVESTMENT_DETAILS_REQUEST = 'INVESTMENT_DETAILS_REQUEST'
export const INVESTMENT_DETAILS_SUCCESS = 'INVESTMENT_DETAILS_SUCCESS'
export const INVESTMENT_DETAILS_FAIL = 'INVESTMENT_DETAILS_FAIL'


export const INVESTMENT_CREATE_REQUEST = 'INVESTMENT_CREATE_REQUEST'
export const INVESTMENT_CREATE_SUCCESS = 'INVESTMENT_CREATE_SUCCESS'
export const INVESTMENT_CREATE_FAIL = 'INVESTMENT_CREATE_FAIL'


export const INVESTMENT_UPDATE_REQUEST = 'INVESTMENT_UPDATE_REQUEST'
export const INVESTMENT_UPDATE_SUCCESS = 'INVESTMENT_UPDATE_SUCCESS'
export const INVESTMENT_UPDATE_FAIL = 'INVESTMENT_UPDATE_FAIL'


export const INVESTMENT_DELETE_REQUEST = 'INVESTMENT_DELETE_REQUEST'
export const INVESTMENT_DELETE_SUCCESS = 'INVESTMENT_DELETE_SUCCESS'
export const INVESTMENT_DELETE_FAIL = 'INVESTMENT_DELETE_FAIL'

