export const INVESTMENT_REQUEST_LIST_REQUEST = 'INVESTMENT_REQUEST_LIST_REQUEST'
export const INVESTMENT_REQUEST_LIST_SUCCESS = 'INVESTMENT_REQUEST_LIST_SUCCESS'
export const INVESTMENT_REQUEST_LIST_FAIL = 'INVESTMENT_REQUEST_LIST_FAIL'


export const INVESTMENT_REQUEST_DELETE_REQUEST = 'INVESTMENT_REQUEST_DELETE_REQUEST';
export const INVESTMENT_REQUEST_DELETE_SUCCESS = 'INVESTMENT_REQUEST_DELETE_SUCCESS';
export const INVESTMENT_REQUEST_DELETE_FAIL = 'INVESTMENT_REQUEST_DELETE_FAIL';


