export const INVESTMENT_REQUEST_LIST_REQUEST = 'INVESTMENT_REQUEST_LIST_REQUEST'
export const INVESTMENT_REQUEST_LIST_SUCCESS = 'INVESTMENT_REQUEST_LIST_SUCCESS'
export const INVESTMENT_REQUEST_LIST_FAIL = 'INVESTMENT_REQUEST_LIST_FAIL'


export const INVESTMENT_REQUEST_DETAILS_REQUEST = 'INVESTMENT_REQUEST_DETAILS_REQUEST'
export const INVESTMENT_REQUEST_DETAILS_SUCCESS = 'INVESTMENT_REQUEST_DETAILS_SUCCESS'
export const INVESTMENT_REQUEST_DETAILS_FAIL = 'INVESTMENT_REQUEST_DETAILS_FAIL'


export const INVESTMENT_REQUEST_CREATE_REQUEST = 'INVESTMENT_REQUEST_CREATE_REQUEST'
export const INVESTMENT_REQUEST_CREATE_SUCCESS = 'INVESTMENT_REQUEST_CREATE_SUCCESS'
export const INVESTMENT_REQUEST_CREATE_FAIL = 'INVESTMENT_REQUEST_CREATE_FAIL'


export const INVESTMENT_REQUEST_UPDATE_REQUEST = 'INVESTMENT_REQUEST_UPDATE_REQUEST'
export const INVESTMENT_REQUEST_UPDATE_SUCCESS = 'INVESTMENT_REQUEST_UPDATE_SUCCESS'
export const INVESTMENT_REQUEST_UPDATE_FAIL = 'INVESTMENT_REQUEST_UPDATE_FAIL'


export const INVESTMENT_REQUEST_DELETE_REQUEST = 'INVESTMENT_REQUEST_DELETE_REQUEST'
export const INVESTMENT_REQUEST_DELETE_SUCCESS = 'INVESTMENT_REQUEST_DELETE_SUCCESS'
export const INVESTMENT_REQUEST_DELETE_FAIL = 'INVESTMENT_REQUEST_DELETE_FAIL'

