export const INVESTMENT_LIST_REQUEST = 'INVESTMENT_LIST_REQUEST'
export const INVESTMENT_LIST_SUCCESS = 'INVESTMENT_LIST_SUCCESS'
export const INVESTMENT_LIST_FAIL = 'INVESTMENT_LIST_FAIL'


export const INVESTMENT_DELETE_REQUEST = 'INVESTMENT_DELETE_REQUEST';
export const INVESTMENT_DELETE_SUCCESS = 'INVESTMENT_DELETE_SUCCESS';
export const INVESTMENT_DELETE_FAIL = 'INVESTMENT_DELETE_FAIL';

