export const INVESTMENT_LIST_REQUEST = 'INVESTMENT_LIST_REQUEST'
export const INVESTMENT_LIST_SUCCESS = 'INVESTMENT_LIST_SUCCESS'
export const INVESTMENT_LIST_FAIL = 'INVESTMENT_LIST_FAIL'


export const INVESTMENT_DELETE_REQUEST = 'INVESTMENT_DELETE_REQUEST';
export const INVESTMENT_DELETE_SUCCESS = 'INVESTMENT_DELETE_SUCCESS';
export const INVESTMENT_DELETE_FAIL = 'INVESTMENT_DELETE_FAIL';


export const INVESTMENT_STATUS_CHANGE_REQUEST = 'INVESTMENT_STATUS_CHANGE_REQUEST';
export const INVESTMENT_STATUS_CHANGE_SUCCESS = 'INVESTMENT_STATUS_CHANGE_SUCCESS';
export const INVESTMENT_STATUS_CHANGE_FAIL = 'INVESTMENT_STATUS_CHANGE_FAIL';
