export const NEWS_BLOGS_LIST_REQUEST = 'NEWS_BLOGS_LIST_REQUEST'
export const NEWS_BLOGS_LIST_SUCCESS = 'NEWS_BLOGS_LIST_SUCCESS'
export const NEWS_BLOGS_LIST_FAIL = 'NEWS_BLOGS_LIST_FAIL'


export const NEWS_BLOGS_DETAILS_REQUEST = 'NEWS_BLOGS_DETAILS_REQUEST'
export const NEWS_BLOGS_DETAILS_SUCCESS = 'NEWS_BLOGS_DETAILS_SUCCESS'
export const NEWS_BLOGS_DETAILS_FAIL = 'NEWS_BLOGS_DETAILS_FAIL'


export const NEWS_BLOGS_CREATE_REQUEST = 'NEWS_BLOGS_CREATE_REQUEST'
export const NEWS_BLOGS_CREATE_SUCCESS = 'NEWS_BLOGS_CREATE_SUCCESS'
export const NEWS_BLOGS_CREATE_FAIL = 'NEWS_BLOGS_CREATE_FAIL'


export const NEWS_BLOGS_UPDATE_REQUEST = 'NEWS_BLOGS_UPDATE_REQUEST'
export const NEWS_BLOGS_UPDATE_SUCCESS = 'NEWS_BLOGS_UPDATE_SUCCESS'
export const NEWS_BLOGS_UPDATE_FAIL = 'NEWS_BLOGS_UPDATE_FAIL'


export const NEWS_BLOGS_DELETE_REQUEST = 'NEWS_BLOGS_DELETE_REQUEST'
export const NEWS_BLOGS_DELETE_SUCCESS = 'NEWS_BLOGS_DELETE_SUCCESS'
export const NEWS_BLOGS_DELETE_FAIL = 'NEWS_BLOGS_DELETE_FAIL'

