export const NEWS_BLOGS_LIST_REQUEST = 'NEWS_BLOGS_LIST_REQUEST'
export const NEWS_BLOGS_LIST_SUCCESS = 'NEWS_BLOGS_LIST_SUCCESS'
export const NEWS_BLOGS_LIST_FAIL = 'NEWS_BLOGS_LIST_FAIL'


export const NEWS_BLOGS_DELETE_REQUEST = 'NEWS_BLOGS_DELETE_REQUEST';
export const NEWS_BLOGS_DELETE_SUCCESS = 'NEWS_BLOGS_DELETE_SUCCESS';
export const NEWS_BLOGS_DELETE_FAIL = 'NEWS_BLOGS_DELETE_FAIL';


export const NEWS_BLOGS_ADD_REQUEST = 'NEWS_BLOGS_ADD_REQUEST';
export const NEWS_BLOGS_ADD_SUCCESS = 'NEWS_BLOGS_ADD_SUCCESS';
export const NEWS_BLOGS_ADD_FAIL = 'NEWS_BLOGS_ADD_FAIL';

export const NEWS_BLOGS_EDIT_REQUEST = 'NEWS_BLOGS_EDIT_REQUEST';
export const NEWS_BLOGS_EDIT_SUCCESS = 'NEWS_BLOGS_EDIT_SUCCESS';
export const NEWS_BLOGS_EDIT_FAIL = 'NEWS_BLOGS_EDIT_FAIL';