export const NEWS_BLOGS_LIST_REQUEST = 'NEWS_BLOGS_LIST_REQUEST'
export const NEWS_BLOGS_LIST_SUCCESS = 'NEWS_BLOGS_LIST_SUCCESS'
export const NEWS_BLOGS_LIST_FAIL = 'NEWS_BLOGS_LIST_FAIL'


export const NEWS_BLOGS_DELETE_REQUEST = 'NEWS_BLOGS_DELETE_REQUEST';
export const NEWS_BLOGS_DELETE_SUCCESS = 'NEWS_BLOGS_DELETE_SUCCESS';
export const NEWS_BLOGS_DELETE_FAIL = 'NEWS_BLOGS_DELETE_FAIL';


