export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST'
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS'
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL'


export const USERS_DETAILS_REQUEST = 'USERS_DETAILS_REQUEST'
export const USERS_DETAILS_SUCCESS = 'USERS_DETAILS_SUCCESS'
export const USERS_DETAILS_FAIL = 'USERS_DETAILS_FAIL'


export const USERS_CREATE_REQUEST = 'USERS_CREATE_REQUEST'
export const USERS_CREATE_SUCCESS = 'USERS_CREATE_SUCCESS'
export const USERS_CREATE_FAIL = 'USERS_CREATE_FAIL'


export const USERS_UPDATE_REQUEST = 'USERS_UPDATE_REQUEST'
export const USERS_UPDATE_SUCCESS = 'USERS_UPDATE_SUCCESS'
export const USERS_UPDATE_FAIL = 'USERS_UPDATE_FAIL'


export const USERS_DELETE_REQUEST = 'USERS_DELETE_REQUEST'
export const USERS_DELETE_SUCCESS = 'USERS_DELETE_SUCCESS'
export const USERS_DELETE_FAIL = 'USERS_DELETE_FAIL'

